name: algua
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python
  - python=3.11.5
  
  # Core Data Science
  - pandas=2.1.1
  - numpy=1.24.3
  - scipy=1.11.2
  - scikit-learn=1.3.0
  
  # Trading & Financial Analysis
  - ta-lib=0.4.25
  
  # Deep Learning
  - pytorch=2.0.1
  - pytorch-lightning=2.0.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  
  # Optimization & ML
  - optuna=3.3.0
  
  # Web Framework
  - fastapi=0.103.1
  - uvicorn=0.23.2
  - pydantic=2.3.0
  
  # Dashboard
  - streamlit=1.26.0
  
  # Testing
  - pytest=7.4.2
  - pytest-cov=4.1.0
  - pytest-asyncio=0.21.1
  
  # Development Tools
  - black=23.7.0
  - isort=5.12.0
  - flake8=6.0.0
  - pre-commit=3.4.0
  
  # Utilities
  - requests=2.31.0
  - python-dotenv=1.0.0
  - click=8.1.7
  - pyyaml=6.0.1
  - jinja2=3.1.2
  
  # Jupyter
  - jupyter=1.0.0
  - jupyterlab=4.0.6
  
  # pip packages
  - pip=23.2.1
  - pip:
    # VectorBT Pro (requires license)
    - vectorbtpro>=1.0.0
    # Trading APIs
    - alpaca-trade-api==3.1.1
    - alpaca-py==0.9.0
    # Monitoring
    - wandb==0.15.10
    # TradingView data
    - tvdatafeed==2.1.3
    # Telegram bot
    - python-telegram-bot==20.5
    # Additional utilities
    - yfinance==0.2.20
    - ccxt==4.0.102
    # Data validation
    - cerberus==1.3.4
    # Progress bars
    - tqdm==4.66.1
    # Scheduling
    - schedule==1.2.0

# Note: Install separately via system package manager:
# - rclone (for cloud storage sync)
# - gsutil (for Google Cloud Storage) 