name: algua
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python
  - python=3.11.5
  
  # Core Data Science
  - pandas=2.1.1
  - numpy=1.24.3
  - scipy=1.11.2
  - scikit-learn=1.3.0
  
  # Deep Learning
  - pytorch=2.0.1
  - pytorch-lightning=2.0.8
  
  # Optimization & ML
  - optuna=3.3.0
  
  # Web Framework
  - fastapi=0.103.1
  - uvicorn=0.23.2
  - pydantic=2.3.0
  
  # Dashboard
  - streamlit=1.26.0
  
  # Testing
  - pytest=7.4.2
  - pytest-cov=4.1.0
  - pytest-asyncio=0.21.1
  
  # Development Tools
  - black=23.7.0
  - isort=5.12.0
  - flake8=6.0.0
  - pre-commit=3.4.0
  
  # Utilities
  - requests=2.31.0
  - python-dotenv=1.0.0
  - click=8.1.7
  - pyyaml=6.0.1
  - jinja2=3.1.2
  
  # Jupyter
  - jupyter=1.0.0
  - jupyterlab=4.0.6
  
  # pip packages
  - pip=23.2.1
  - pip:
    # Essential trading packages only
    - yfinance==0.2.20
    - schedule==1.2.0
    # Data validation
    - cerberus==1.3.4