"""Strict inventory and isolated verification of frozen planner environments."""
from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import subprocess
import sys
from email.parser import HeaderParser
from pathlib import Path

from algua.registry.artifact_contract import ArtifactFile
from algua.registry.environment_contract import (
    BASE_INTERPRETER,
    InstalledDistribution,
    InstalledInventory,
    InterpreterIdentity,
    InterpreterLink,
)
from algua.registry.planner_environment_errors import EnvironmentIncompatible

_CHUNK_SIZE = 1024 * 1024
_SEPARATOR_RUN = re.compile(r"[-_.]+")


def scrubbed_environment(binary_path: Path, *, home: Path | None = None) -> dict[str, str]:
    """Return a replacement environment, never a filtered copy of inherited authority."""
    locale = os.environ.get("LANG", "C.UTF-8")
    return {
        "HOME": str(home) if home is not None else "/nonexistent",
        "PATH": str(binary_path),
        "PYTHONDONTWRITEBYTECODE": "1",
        "LANG": locale,
        "LC_ALL": os.environ.get("LC_ALL", locale),
    }


def _metadata_identity(raw: str) -> InstalledDistribution:
    """Read exactly one Name and Version from the header block, never the description body."""
    headers = HeaderParser().parsestr(raw)
    names = headers.get_all("Name") or []
    versions = headers.get_all("Version") or []
    if len(names) != 1 or len(versions) != 1:
        raise EnvironmentIncompatible("installed distribution metadata is incomplete")
    name = _SEPARATOR_RUN.sub("-", str(names[0]).strip()).lower()  # PEP 503 canonical name
    if name == "algua":
        raise EnvironmentIncompatible("installed Algua distribution is forbidden")
    try:
        return InstalledDistribution(name, str(versions[0]).strip())
    except ValueError as exc:
        raise EnvironmentIncompatible("installed distribution identity is malformed") from exc


def _file_digest(path: Path) -> tuple[int, str]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while chunk := handle.read(_CHUNK_SIZE):
            size += len(chunk)
            digest.update(chunk)
    return size, digest.hexdigest()


def _interpreter_link(root: Path, path: Path) -> InterpreterLink:
    required = {"python", "python3", f"python{sys.version_info.major}.{sys.version_info.minor}"}
    if path.parent != root / "bin" or path.name not in required:
        raise EnvironmentIncompatible("environment contains an unexpected symlink")
    resolved = path.resolve(strict=True)
    base = Path(getattr(sys, "_base_executable", sys.executable)).resolve()
    raw_target = Path(os.readlink(path))
    if raw_target.is_absolute():
        if resolved != base:
            raise EnvironmentIncompatible("interpreter link escapes its keyed base interpreter")
        target = BASE_INTERPRETER
    else:
        if resolved != base and root.resolve() not in resolved.parents:
            raise EnvironmentIncompatible("interpreter link escapes its environment")
        lexical_target = Path(os.path.normpath(path.parent / raw_target))
        try:
            target = lexical_target.relative_to(root).as_posix()
        except ValueError as exc:
            raise EnvironmentIncompatible("interpreter link escapes its environment") from exc
    return InterpreterLink(path.relative_to(root).as_posix(), target)


def inventory_environment(root: Path) -> InstalledInventory:
    if root.is_symlink() or not root.is_dir():
        raise EnvironmentIncompatible("environment root is not a real directory")
    files: list[ArtifactFile] = []
    links: list[InterpreterLink] = []
    distributions: list[InstalledDistribution] = []
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        directory = Path(dirpath)
        for name in dirnames:
            if (directory / name).is_symlink():
                raise EnvironmentIncompatible("environment contains an unexpected symlink")
        for name in filenames:
            path = directory / name
            if path.is_symlink():
                links.append(_interpreter_link(root, path))
                continue
            info = path.lstat()
            if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
                raise EnvironmentIncompatible(
                    "environment contains a non-regular or hardlinked file"
                )
            if path.suffix in {".pyc", ".pyo"} or "__pycache__" in path.parts:
                raise EnvironmentIncompatible("environment contains generated bytecode")
            size, digest = _file_digest(path)
            relative = path.relative_to(root).as_posix()
            mode = "100755" if info.st_mode & stat.S_IXUSR else "100644"
            files.append(ArtifactFile(relative, mode, size, digest))
            if path.name == "METADATA" and path.parent.name.endswith(".dist-info"):
                distributions.append(_metadata_identity(path.read_text(encoding="utf-8")))
    names = [item.name for item in distributions]
    if len(set(names)) != len(names):
        raise EnvironmentIncompatible("environment has duplicate installed distributions")
    versioned_python = f"bin/python{sys.version_info.major}.{sys.version_info.minor}"
    expected_links = {"bin/python", "bin/python3", versioned_python}
    if {link.path for link in links} != expected_links:
        raise EnvironmentIncompatible("environment interpreter link inventory is incomplete")
    files.sort(key=lambda item: item.path.encode())
    links.sort(key=lambda item: item.path.encode())
    distributions.sort(key=lambda item: (item.name, item.version))
    return InstalledInventory(tuple(distributions), tuple(files), tuple(links))


def verify_environment(
    root: Path, expected_interpreter: InterpreterIdentity, expected_inventory_digest: str,
) -> None:
    inventory = inventory_environment(root)
    if inventory.digest != expected_inventory_digest:
        raise EnvironmentIncompatible("installed environment inventory drifted")
    python = root / "bin/python"
    probe = (
        "import importlib.util,json,platform,sys,sysconfig;"
        "print(json.dumps({'implementation':platform.python_implementation(),"
        "'version':platform.python_version(),'cache_tag':sys.implementation.cache_tag or 'unknown',"
        "'soabi':sysconfig.get_config_var('SOABI') or 'unknown',"
        "'platform_tag':sysconfig.get_platform(),'os_name':platform.system().lower(),"
        "'machine':platform.machine().lower(),"
        "'algua':importlib.util.find_spec('algua') is not None}))"
    )
    try:
        result = subprocess.run(
            [str(python), "-I", "-c", probe], cwd=root,
            env=scrubbed_environment(python.parent), check=True, capture_output=True,
            text=True, timeout=30,
        )
        observed = json.loads(result.stdout)
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError) as exc:
        raise EnvironmentIncompatible(
            "published environment interpreter verification failed"
        ) from exc
    has_algua = observed.pop("algua", None)
    if has_algua is not False or observed != expected_interpreter.to_dict():
        raise EnvironmentIncompatible("published environment interpreter identity drifted")
